### ISSUE TITLE
Multiple encounters should not exist within a single FHIR bundle (confirmed with v0.10.4)

### ISSUE THREAD

**Issue by n-kes** [qe-collaborative-services/1115-hub#102]
We are seeing that some bundles are coming from QCS QE's (at least HealtheLink and HealtheConnections, possibly others?) that have multiple encounters in a single bundle. 

This is one of the validation rules enforced by the data lake, so per Michael and Rachel's input we should enhance both the QCS and NYeC processing and validation engines to not allow multiple Encounter profiles in a single Bundle.

Examples:

|                                    Bundle ID                                    |         QE         | Encounter count | Approx. time of NYeC ingestion |
|---------------------------------------------------------------------------------|--------------------|-----------------|--------------------------------|
| 095ae860-f1a3-11ee-8867-496c71dbb7a6_healthelink-20240403-testcase1-MRN         | healthelink        |               3 | 2024-04-03T10:15:07.872Z       |
| bbf171b0-f1a3-11ee-9845-1568ccac58fc_healthelink-20240403-testcase1-MRN         | healthelink        |               3 | 2024-04-03T10:20:06.260Z       |
| 89c96f10-f1d2-11ee-9628-236c17b56884_healtheconnections-20240327-testcase47-MRN | healtheconnections |               2 | 2024-04-03T15:55:12.403Z       |
| 553b1ed0-f1d5-11ee-a1e0-8532d240f8d1_healtheconnections-20240327-testcase52-MRN | healtheconnections |               2 | 2024-04-03T16:15:23.941Z       |

@raphaelvp @reeager @shah

**Comment by reeager** [comment]
This issue should be followed not #79. There should be a single encounter per bundle.

**Comment by raphaelvp** [comment]
@reeager, thanks for the clarification. We have started the changes. This will be updated in the next release 0.12.0 by April 5 8:00 AM EDT.

**Comment by DrewMcN** [comment]
If we can have the release deployed by 7:30 that would be great as we expect to test early

**Comment by raphaelvp** [comment]
@DrewMcN, OK. We will make it by 7:30 AM.

**Comment by raphaelvp** [comment]
Resolved by #105. Released in 0.12.0
