### ISSUE TITLE
Patient.identifier.system values should be a uri with "facility" in the path

### ISSUE THREAD

**Issue by ghoward9** [qe-collaborative-services/1115-hub#104]
Every bundle should always have a /facility/ keyword in patient.identifier.system where code='MR' the value should be a uri. This is a validation rule enforced by the data lake team and the modification should be made in QCS and NYeC processing.

@raphaelvp @reeager @shah

**Comment by n-kes** [comment]
@ghoward9, the context here is that having that known name-value pair for each QE in the MRN identifier allows us to identify the QE that the screening is submitted from? This prevents us from having to rely on the (unfortunately unreliable) query parameter in the API call, correct?

**Comment by raphaelvp** [comment]
`patient.identifier.system` is currently mapped from `QE_ADMIN_DATA.FACILITY_ID` when code="MR". As per this ticket, this will be updated to `"/facility/"+QE_ADMIN_DATA.FACILITY_ID`. This will be released in v0.12.0 today.

**Comment by raphaelvp** [comment]
Resolved by #105, Released in 0.12.0
