### ISSUE TITLE
Ensure there are unique logical ids for observations

### ISSUE THREAD

**Issue by reeager** [qe-collaborative-services/1115-hub#108]
Please ensure ids are unique for each observation. Please see Manny's description once he sends this out and the observation.id description in the FHIR IG. 
https://djq7jdt8kb490.cloudfront.net/1115/StructureDefinition-shin-ny-observation-screening-response-definitions.html#key_Observation.id

**Comment by reeager** [comment]
@shah @raphaelvp @DrewMcN

**Comment by fredharmonbcbsscgit** [comment]
While it is true that from a pure FHIR standpoint, the resource ID's only need to be unique within a given bundle, the Data Lake team is using those observation ID's across all patients and all time.  Typically you should not use the FHRI resource ID coming to you as your own unqiue internal identifier but in this case there must be a reason Data Lake is doing so.  If we could make the id ""id": "observationResponseQuestion_13",  (for example), somehow more unique globally (perhaps append a GUID at the end), then it should resolve the Data Lake issue.

**Comment by shah** [comment]
@fredharmonbcbsscgit and @reeager we're investigating the options now and will get back to you with our preference. The tricky part is that the Data Lake would like the uniqueness to be across all patients and all time, but QCS (at this time, during synthetic period) is processing the data and sending it out without retaining the data long-term in a central database.

We'd have to consider these options:

- **either**: Data Lake could relax the uniqueness across all patients and all time and accept the values as-is for the synthetic test period and figure out how to handle it in production later
- **or**: Data Lake keeps the uniqueness across all patients and all-time requirement and:
  - **either**: have the QEs enrich / update the CSVs with the unique IDs that can be maintained on their side -- in this case QCS would simply pass the values through from the QEs
    - this is the most work on QEs, least on QCS
  - **or**: QCS can create UUIDv5 (which are idempotent) tied to the MPID as the UUIDv5 namespace; QCS can handle this on its own without necessarily asking the QEs to do anything specific
    -  this would be some real work for QCS, but easy for QEs
  - **or**: QCS can create a stateful system (e.g. PostgreSQL or something) to maintain the previously generated IDs and look them up from prior calls 
    - this is the hardest for QCS (non-trivial architecture change), easy for QEs

Do these options make sense or are we missing anything?

**Comment by reeager** [comment]
Please see Luca's response:

The approach of adding a UUID will not work because DL functions as an upsert model, and an UUID will make it an append-only model. The root requirement is that we want an updated observation to have the same id of the older one in order to make an update, but if you use an UUID, all observations will be treated as new, creating redundances.
Moreover, if you plan to use UUIDv5 (MPID + GUID), that has also created redundancies in the past, as the MPID can change over time. For example, Bronx was using MPID in their patient logical id and it caused redundances since MPIDs can change quite often, hence our recommendation was to not use MPID when creating a resource id.

**Comment by reeager** [comment]
I think right now we just need an ID for tomorrow in the observation.id that is universally unique.

**Comment by shah** [comment]
Sounds good @reeager, for now we'll make it unique within the ingress set (perhaps including a QE symbol in there as well) and then later give more thought to how we'd be able to make it unique across time. If we know how Bronx is generating the identity and ensure uniqueness over time perhaps we can learn from their experience.

**Comment by raphaelvp** [comment]
To make the Observation ID unique, we are implementing at as a concatenated value based on the pattern: observationResponseQuestion-<PAT_MRN_ID>-<FACITLITY_ID>-<QUESTION_SLNO>.

**Comment by reeager** [comment]
This aligns similarly with what Bronx RHIO is doing. Thank you for your work on this!

**Comment by alan-francis** [comment]
@reeager : We are planning to add the `RECORDED_TIME` from the `screening` and encrypt that value before concatenating it to the Observation ID. By doing this we can be sure that even if a `RECORDED_TIME` value coming from the incoming files is not in a valid date-time format, the query will not throw an error.

@shah @raphaelvp

**Comment by raphaelvp** [comment]
Resolved by #113. Released in 0.13.0
