### ISSUE TITLE
Identify process for scanning code

### ISSUE THREAD

**Issue by hgallson** [qe-collaborative-services/1115-hub#11]
- [ ] identify tool (e.g. Veracode)
- [ ] identify who is responsible for running code scans (e.g. QE, QCS)
- [ ] determine process for running code, including frequency

**Comment by shah** [comment]
@hgallson our plan should be to use GitHub Actions for all code scanning. The core engineering team will be responsible for running code scans and it should be run monthly.

**Comment by shah** [comment]
Added initial scan and setup weekly cron job. See [initial report](https://github.com/qe-collaborative-services/1115-hub/actions/runs/7662088579).
