### ISSUE TITLE
Incorrect patient references from other resources

### ISSUE THREAD

**Issue by fredharmonbcbsscgit** [qe-collaborative-services/1115-hub#119]
[healthelink_20240415_testcase1_receivedBundle_2024-04-15_22-09-37.json](https://github.com/qe-collaborative-services/1115-hub/files/15014815/healthelink_20240415_testcase1_receivedBundle_2024-04-15_22-09-37.json)

You can use the attached file as a reference but this issue is across the board.

The Patient FHIR ID is "CNYSCN-healthelink-20240415-testcase1-MRN"

The Consent and Observation resources incorrectly reference to "reference": "Patient/healthelink-20240415-testcase1-MRN".  Some of the other resource types (Encounter) have it refernced correctly like "reference": "Patient/CNYSCN-healthelink-20240415-testcase1-MRN"

@shah @raphaelvp @mdvertola

**Comment by shah** [comment]
Released in `v0.15.0`, assumed to be working. Please reopen in case of regression.
