### ISSUE TITLE
Prepare SFTP-based file acquisition, processing, and response infrastructure

### ISSUE THREAD

**Issue by shah** [qe-collaborative-services/1115-hub#12]
For the "QCS Only" architecture:

- [x] Define SFTP authentication strategy
  - [x] Simple per-QE username and password during synthetic data trials (before April)
- [x] Define SFTP acquisition directory patterns
  - [x] `<root>/qe/<qe-identity>/ingress` is "incoming directory"
  - [x] `<root>/qe/<qe-identity>/egress/<session-id>` is "outgoing directory" for validation, diagnostics, and other artifacts that QEs should pick up files from; 
  - [x] `<root>/qe/<qe-identity>/egress/<session-id>/.workflow` is "while processing directory"
  - [x] `<root>/qe/<qe-identity>/egress/<session-id>/.consumed` is "archive directory" for all `ingress` files that have completed processing
- [x] As files arrive in `ingress` they should be processed by the code and placed into proper directories
  - [x] Files matching pattern `screening(.*?).csv`, `qe_admin_data(.*?).csv` and `demographics(.*?).csv` will be consumed and all other files will be ignored and reported as an error. As long as the `(.*?)` regular expression content matches the same text for the three files they will be treated as a "group".

**Comment by mfrey27** [comment]
Currently RRHIO anticipated having an outbound (QE to QCS) repository within the QE infrastructure that QCS would pull and push from\into.  The comments above would suggest rather that the QE will pull and push from a repository sitting within QCS. Either should work but is this part of the design defined?

**Comment by shah** [comment]
Good question @mfrey27 - currently the design is for the QE to collect the data in its own infrastructure (using any mechanism it desire), enrich the data with MPI details within the QE's infrastructure, and then from the QE's infrastructure send the data to the QCS infrastructure using SFTP. From that point the QCS infrastructure will parse, validate, create FHIR bundle, and forward to SHIN-NY.

**Comment by mfrey27** [comment]
Thanks @shah  - to confirm the QE would also pull notifications (success, errors, etc.) from QCS as well (vs QCS pushing to QE).  Assuming correct we will need to have the details soon to complete our design for file retrieval and processing.

**Comment by shah** [comment]
Correct @mfrey27 the QE will pull validation results from their `egress` directory and we'll include that in the specification (it's mentioned in the ticket body above).

**Comment by shah** [comment]
The SFTP infrastructure is built and deployed per the original spec.
