### ISSUE TITLE
Introduce FHIR ingestion service

### ISSUE THREAD

**Issue by shah** [qe-collaborative-services/1115-hub#123]
See [TechBD Docs](https://tech-by-design.github.io/docs.techbd.org/1115-hub/fhir-services/) for proposed data flows, sequences, and architecture.

**Iteration 1** (infrastructure, version `0.20.0`)
- [x] Prepare FHIR service to accept bundles in the same format as SHIN-NY Data Lake
  - [x] `/Bundle/$validate` endpoint which validates, stores session diagnostics in memory but does not submit to Data Lake
  - [x] `/metadata` endpoint (typical FHIR) which can act as a health check as well as capabilities reporter
- [x] Validate using FHIR Implementation Guide (IG)
  - [x] Allow _dry-run_ capability (stateless validation only)
  - [x] Store stateful validation sessions diagnostics in memory (as HTTP server `sessions` property) for retrieval
- [x] JUnit unit tests for orchestration session (not HTTP) happy path and unhappy path
- [x] httpYac end-to-end (`e2e`) integration tests for HTTP happy path and unhappy path
  - [x] Update and explain `e2e` test output in [support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service](https://github.com/qe-collaborative-services/1115-hub/tree/main/support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service)

**Iteration 2** (infrastructure continuation, version `0.22.0`)
- [x] Accept QE identifier as HTTP Header `TECH_BD_FHIR_SERVICE_QE_IDENTIFIER` and incorporate it into the session as `qeIdentifier`.
- [x] Ensure rules match HAPI FHIR default validator.
- [x] Report all FHIR and IG errors in the response, not just the first error.
- [x] Enhanced JUnit unit tests to include NYeC test cases
- [x] Enhanced httpYac integration tests to include NYeC test cases
  - [x] Update and explain `e2e` test output in [support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service](https://github.com/qe-collaborative-services/1115-hub/tree/main/support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service)
- [x] `/admin/diagnostics/<session-id>` which retrieves session diagnostics from HTTP server `sessions` property for previously run sessions

**Iteration 3** (submit validated content to Data Lake, version `0.23.0`)
- [x] `/metadata` endpoint (typical FHIR)
- [x] `/Bundle` endpoint which validates, stores content and validation diagnostics, and submits to Data Lake
  - [x] Submission to the Data Lake should be done in a separate thread / async and its result should be stored into session after async completion
  - [x] Read the Data Lake API endpoint from a property file by default but accept HTTP Header `TECH_BD_FHIR_SERVICE_SHINNY_DATALAKE_API_URL` and allow overriding the destination.
- [x] Ensure low to medium complexity JSON payloads can be processed within 3 seconds
- [x] orchestration session should include caller's full request (including IP address, etc.) to indicate source of request
  - [ ] the `deviceId` should be the `hostname` where the server is running
- [x] `/admin/diagnostics` which retrieves all session diagnostics information from HTTP server `sessions` for previously run sessions
  - [x] include IP address and other caller details
- [x] Enhanced httpYac integration tests to include NYeC test cases
  - [x] Update and explain `e2e` test output in [support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service](https://github.com/qe-collaborative-services/1115-hub/tree/main/support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service)
- [x] Add a home page for FHIR Server which points to the Swagger API documentation
- [ ] Figure out how to give full Java servlet request/response logging details to end users

**Iteration 4** (filterable validation and SQL storage)
- [ ] Support multiple validation engines: ensure rules match Inferno via [either a service](https://github.com/hapifhir/org.hl7.fhir.validator-wrapper) or using the same library code bundled into 1115-Hub JAR.
- [ ] Check FHIR IG profile parsing and other FHIR Validator contexts to see if they can be cached once in the service startup and not done once per each session
- [ ] Store stateful validation sessions diagnostics in database for retrieval
- [ ] Integrate AG-Grid to display /admin/diagnostics informaion so that users can interactively analyze the diagnostics information
- [ ] Define schema for FHIR IG validation rules that should be ignored / filtered / rewritten in tables
  - [ ] Create URL parameters or headers to filter out issues in specific sessions (to override defaults)
- [ ] Define schema for feature flags to determine behaviors within the database instead of service code
- [ ] `/db` endpoint which proxies to [PostgREST](https://postgrest.org/en/v12/)
- [ ] `/admin/db` endpoint which is a [pgweb](https://sosedoff.github.io/pgweb/) endpoint proxy (each QE has their own username/password for read-only data)
- [ ] `/diagnostics/<session-id>` endpoint retrieves session diagnostics from in database for previously run sessions
- [ ] `/admin/quality/smoke-test` endpoint which runs `httpYac` binary CLI and prepares TAP or HTML results for display
- [ ] Enhanced JUnit unit tests to include more NYeC test cases
  - [ ] Add performance/timing tests to ensure synchronous response occurs within expected timeframe
- [ ] Enhanced httpYac integration tests to more include NYeC test cases
  - [ ] Add performance/timing tests to ensure synchronous response occurs within expected timeframe
  - [ ] Update and explain `e2e` test output in [support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service](https://github.com/qe-collaborative-services/1115-hub/tree/main/support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service)
- [ ] `/admin/docs/api` endpoint which mounts Swagger documentation generated using [fhir-oas](https://github.com/Sheep-inc/fhir-oas)
- [ ] `/admin/validate` which performs all the same actions as `/Bundle/$validate` except returns the diagnostics as HTML similar to Inferno instead of as JSON

**Iteration 5** (SQL retrieval)
- [ ] Create `MPI` SQL views to allow QEs to query patient demographics for sync'ing their MPIs.
  - [ ] All QEs can use `/db/*` authenticated query endpoints
  - [ ] For QEs that request it, submit MPI change data capture (CDC) via STP
- [ ] Evaluate and use [pgmq](https://github.com/tembo-io/pgmq) for SQS type queues within PostgreSQL.
- [ ] Deploy httpYac or other stress testing system to simulate multiple SCNs and QEs coming in simultaneously.
- [ ] Implement transformations layer if required (needs NYeC decision)
- [ ] Implement [sql-on-fhir-v2](https://github.com/FHIR/sql-on-fhir-v2) querying from content stored in PostgreSQL.
- [ ] Evaluate the integration of FHIR Validation functionalities in AWS Lambda

**Iteration 6** (realign CSV business logic to match FHIR business logic)
- [ ] Pass generated FHIR from CSV orchestration process through this FHIR server to ensure validation rules adhere to business logic required by this FHIR server
- [ ] Consider generating CSV validation SQL logic from FHIR IG so that reading CSV and reading FHIR uses the same business rules (the FHIR IG profile)

![qcs-fhir-service.drawio.svg](https://raw.githubusercontent.com/tech-by-design/docs.techbd.org/main/public/content/docs/1115-hub/fhir-services/qcs-fhir-service.drawio.svg)

**Comment by vinodaravind01** [comment]
Selected HAPI FHIR server for FHIR implementation. Completed the creation of two endpoints for FHIR Server (HAPI) validation and submission for this requirement. The validation endpoint checks the input bundle and performs a dry run. Both endpoints convert the input FHIR Bundle to three CSVs.

Implemented a query parameter feature to accept parameters like qe=xzy, persist-diagnostics=no, and enrichment-hook=xyz.

The FHIR server now accepts command-line arguments and starts accordingly. Sample command expectations are mvn jetty:run --Djetty.port=PORT -Djetty.host=HOST_IP -Dargs:HTTPEndpoint=VALUE .  The validation endpoint will call the orchestration HTTP service with submit-shin-ny = no, while the creation endpoint will call with submit-shin-ny = true.

**Pending:**

Testing the functionalities using the orchestration HTTP service.
Enhancing the submission response according to the request.

**Comment by shah** [comment]
Test cases, results and examples of diagnostics for Friday May 3, 2024 are available in [support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service/2024-05-03](../tree/main/support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service/2024-05-03).

**Comment by n-kes** [comment]
Attached are two FHIR test/result sets (one from Bronx and one from QCS - HeC in this case). These are current samples, so there may be a few fields that require some adjustments based on further refinements to the implementation guide as they are made, but they should be closely representative of the final product.

[fhir_examples.zip](https://github.com/qe-collaborative-services/1115-hub/files/15225462/fhir_examples.zip)

@reeager @raphaelvp @mdvertola

**Comment by raphaelvp** [comment]
Added Test cases, results and examples of diagnostics including the above test cases from Bronx and HeC for May 7, 2024. These are available in [support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service/2024-05-07](../tree/main/support/assurance/ahc-hrsn-elt/screening/results-test-e2e/fhir-service/2024-05-07).

**Comment by raphaelvp** [comment]
Development of Iteration 2 is in progress. Next release will be updated by May 8, 2024 7:30 am EDT.

**Comment by shah** [comment]
Migration of FHIR to new TechBD Polyglot Prim monorepo is complete.
