### ISSUE TITLE
Clarification needed on validation rules specified in Omnibus FHIR Rules

### ISSUE THREAD

**Issue by ratheesh-kr** [qe-collaborative-services/1115-hub#125]
Based the latest omnibus FHIR excel document the following rules needs clarification.

- [x] Row 26: `SCREENING_CODE_DESCRIPTION` QCS need clarification on Permissible Values
- [x] Row 27: `SCREENING_CODE_SYSTEM_NAME` QCS need clarification on Permissible Values
- [x] Row 28: `SCREENING_CODE` QCS need clarification on Permissible Values
- [x] Row 29: `RECORDED_TIME` QCS need clarification on Permissible Values
- [x] Row 30: `QUESTION_CODE_DESCRIPTION` QCS need clarification on Permissible Values
- [x] Row 31: `ANSWER_CODE_DESCRIPTION` QCS need clarification on Permissible Values
- [x] Row 32: `UCUM_UNITS` QCS need clarification on Permissible Values
- [ ] Row 55: `Race code.system` QCS need clarification on Permissible Values, the given values are  `'CDC', 'CDCRE', '2.16.840.1.113883.6.23'` please  confirm the third permissible value, in reference [URL](https://terminology.hl7.org/3.1.0/CodeSystem-CDCREC.html) which seems `urn:oid:2.16.840.1.113883.6.238`
QCS 
- [ ] Row 58: `Ethnicity code.system`  QCS need clarification on Permissible Values, the given values are  `'CDC', 'CDCRE', '2.16.840.1.113883.6.23'` please  confirm the third permissible value, in reference [URL](https://terminology.hl7.org/3.1.0/CodeSystem-CDCREC.html) which seems `urn:oid:2.16.840.1.113883.6.238`
QCS 

need clarification on the Permissible Values for Rows 26 to 32, 55 and 58

@reeager

**Comment by shah** [comment]
@reeager you can put notes into the Excel spreadsheet (for each row) and send it back via email to QCS Help email box or you can add clarification in this ticket directly. The output (FHIR) permissible values might be the same we need to check during ingestion (CSV) as well so we should disambiguate both sides if necessary.

**Comment by ratheesh-kr** [comment]
Row 26 -32 is updated in the revised document.

**Comment by shah** [comment]
All the rules are now in the latest IG.
