### ISSUE TITLE
Tests not being ingested in synthetic.sftp.techbd.org

### ISSUE THREAD

**Issue by ghoward9** [qe-collaborative-services/1115-hub#139]
I sent 15 tests to the production environment today at around 1:30 PM EDT (UTC-4). Those test were not ingested as of 4:08 PM EDT (UTC-4). The tests were for the 'qcs' qualified entity.

**Comment by shah** [comment]
@ghoward9 thanks the report, @mdvertola is investigating and will revert by 4/30. We're in the middle of upgrading all the `*.techbd.org` infrastructure to prepare for FHIR Server deployment so it's we regressed the SFTP server.

**Comment by mdvertola** [comment]
Confirmed with @ghoward9 via email that everything was working as expected and that we are good to close this out.
