### ISSUE TITLE
Observation Logical IDs need to be un-hashed

### ISSUE THREAD

**Issue by reeager** [qe-collaborative-services/1115-hub#145]
Ensure that QCS observation logical IDs are also un-hashed.

**Comment by shah** [comment]
Per @reeager she's checking with RC to see if these need changes or if they're already properly formatted.

**Comment by n-kes** [comment]
The test case generation and certification logic isn't relying on these hashes to be present in any of the responses in order to validate or score them. 
From RC's perspective they can be removed if they are causing a problem at the data lake as long as ID uniqueness is still preserved.

**Comment by shah** [comment]
Per discussion with @reeager, if any change requests are needed, the TechBD team will be provided multiple examples of how to prepare the identifiers.

**Comment by shah** [comment]
Closing in favor of #190
