### ISSUE TITLE
Positive test case that should generate FHIR and a warning is being rejected.

### ISSUE THREAD

**Issue by ghoward9** [qe-collaborative-services/1115-hub#163]
Testcase33 is missing an encounter status code and is being rejected without generating FHIR. The omnibus rules have this as a warning and not a true rejection so FHIR should be generated for this test case.

@reeager

**Comment by ratheesh-kr** [comment]
As per the latest omnibus rules mentioned in this [document](https://nyehealth-my.sharepoint.com/:x:/g/personal/reager_nyehealth_org/EVxWvXAi9VdNs3vxAPAxXqkBZOv_1vaWAA141bEJodQENQ?rtime=JozIhJN43Eg), in Row 25, if the validation for the Encounter status code fails, it will result in a true rejection.

@reeager @shah @raphaelvp
