### ISSUE TITLE
lastUpdated format

### ISSUE THREAD

**Issue by ghoward9** [qe-collaborative-services/1115-hub#166]
lastUpdated should be an instant of the format:
2015-02-07T13:28:17.239+02:00 or 2017-01-01T00:00:00Z

https://hl7.org/fhir/R4/datatypes.html#instant

<img width="755" alt="image" src="https://github.com/qe-collaborative-services/1115-hub/assets/158187027/5f989ac9-b480-4ef6-b702-9838ef2fe558">

**Comment by shah** [comment]
@ghoward9 please explain the issue and what you would like done in which file/code.

**Comment by ghoward9** [comment]
This is for the date formats that are generated when CSV's are sent to techBD.

**Comment by ratheesh-kr** [comment]
@ghoward9

TechBD does not generate date format when the `lastUpdated` field is populated from `RECORDED_TIME`.
The value from `RECORDED_TIME` is directly mapped to the `lastUpdated` field.
Based on the [business rules](https://nyehealth-my.sharepoint.com/:x:/g/personal/reager_nyehealth_org/EVxWvXAi9VdNs3vxAPAxXqkBZOv_1vaWAA141bEJodQENQ?rtime=CTf9eD963Eg), this is not mention as a true rejection, so the FHIR will be generated with values from the CSV.

@shah @raphaelvp

**Comment by ghoward9** [comment]
The data type for lastUpdated is shown in the IG as an instant

https://djq7jdt8kb490.cloudfront.net/1115/StructureDefinition-SHINNYMeta.html

**Comment by ratheesh-kr** [comment]
Updated in version v0.23.6
