### ISSUE TITLE
Identifier.system needs to be a fullURL

### ISSUE THREAD

**Issue by ghoward9** [qe-collaborative-services/1115-hub#172]
In reference to CSV's sent to techBD and the FHIR that is generated from those CSV's

The value for identifier.system needs to be a fullURL

Invalid Example: "/facility/CNYSCN"

Valid Example: ""https://bronx.imat.io/facility/CNYSCN" (This is what Bronx used)

**Comment by ratheesh-kr** [comment]
Updated in version v0.23.6
