### ISSUE TITLE
Organization type codes

### ISSUE THREAD

**Issue by ghoward9** [qe-collaborative-services/1115-hub#175]
In reference to CSV's sent to techBD and the FHIR that is generated from those CSV's

For organization type:

The value needs to be translated to one of the following codes:
https://terminology.hl7.org/5.5.0/CodeSystem-organization-type.html

Or remove organization type as it is not included in the IG

I am seeing invalid codes such as "MA" or "SCN"

**Comment by ratheesh-kr** [comment]
@ghoward9 

Removed the organization type from the FHIR document in release version 0.23.7.

@raphaelvp @shah
