### ISSUE TITLE
CSV display update for "Calculated Physical Activity Score"

### ISSUE THREAD

**Issue by ghoward9** [qe-collaborative-services/1115-hub#179]
The value in column H for physical activity in CSV generation changed from "Calculated weekly physical activity" to "Calculated Physical Activity Score" to match the business rules tab in the omnibus rules.

The new value is "Calculated Physical Activity Score"

**Comment by alan-francis** [comment]
@ghoward9 : We will be updating this change of display in our latest release v0.30.1.

**Comment by raphaelvp** [comment]
Resolved in release v0.30.1
