### ISSUE TITLE
Regression Testing - Error Stating Demographics are Missing

### ISSUE THREAD

**Issue by bbushii** [qe-collaborative-services/1115-hub#189]
Hi QCS Support Team,

HeC sent over all files for regression testing on Thursday, June 6 (around 7am).  Our files were sent, however, within our diagnostics file that we received in egress stated that there were structural issues with our demographics folder. Specifically, the issues are flagging that all required columns are missing, which they are not.

Can we please open up a ticket to investigate this issue with the QCS team? I am attaching the diagnostics file to this message.

Please let me know if anything else is needed. I will be the primary contact for this issue (bbush@healtheconnections.org). Please cc David Rubacha (drubacha@healtheconnections.org) on any email communications.

Best,
Bernard
[diagnostics (3).xlsx](https://github.com/user-attachments/files/15741514/diagnostics.3.xlsx)

**Comment by ratheesh-kr** [comment]
@bbushii 

can you please make sure the following changes are made in the test demographics file.

* Add columns PHONE, SSN in demographics.
* Update the column name SEXUAL_ORIENTATION_DESCRIPTION to SEXUAL_ORIENTATION_CODE_DESCRIPTION.
* Update the column name PREFERRED_LANGUAGE_DESCRIPTION to PREFERRED_LANGUAGE_CODE_DESCRIPTION.

@shah @raphaelvp @alan-francis @reeager

**Comment by raphaelvp** [comment]
Resolved by release v0.40.0
