### ISSUE TITLE
Add workflow processing version strings into all telemetry

### ISSUE THREAD

**Issue by shah** [qe-collaborative-services/1115-hub#19]
- [ ] Introduce versioning of code in `orchestrate.ts` so that any changes in logic or rules uses Semantic Versioning (semver).
- [ ] Add version strings into `orch_session` so that each session knows which code (e.g. TypeScript) and version of code (`vX.Y.Z`) performed the workflow.

**Comment by raphaelvp** [comment]
Resolved by #36
