### ISSUE TITLE
CSV Testcase33 should result in a warning and FHIR should be generated

### ISSUE THREAD

**Issue by ghoward9** [qe-collaborative-services/1115-hub#193]
"Test Case 33 should return a warning back to the SCN about a missing Encounter Status Code.  The QE should add an Encounter Status Code to the file.   FHIR should be generated. "

TechBD is showing REJECTION for this testcase in QE diagnostics.

The Omnibus rules say a missing ENCOUNTER_STATUS_CODE should be a warning not a true rejection and should be resolved by TechBD.

Please deploy this fix at the earliest convenience after Wednesday 6/12/2024.

@raphaelvp @reeager @shah

**Comment by raphaelvp** [comment]
Resolved in v0.40.1
