### ISSUE TITLE
getting 400 bad request response

### ISSUE THREAD

**Issue by skairawala** [qe-collaborative-services/1115-hub#199]
We are getting 400 response for this fhir query end point

https://qo5beg39c8.execute-api.us-east-1.amazonaws.com/dev/HRSNScreening?qe_name=HEALTHIX&source_code=CNYSCN&mrn=222333444&return_all_bundles=1

**Comment by shah** [comment]
@reeager since this is for a non-QCS asset where should @skairawala post questions / issues about the HRSN Screening APIs?
