### ISSUE TITLE
Race/Ethnicity need to be OMB category only for those OMBcategories. The rest should be detailed.

### ISSUE THREAD

**Issue by reeager** [qe-collaborative-services/1115-hub#201]
<img width="780" alt="image" src="https://github.com/qe-collaborative-services/1115-hub/assets/141359696/1c252bc9-4fde-4a2d-9638-2b08118316d6">

Please see IG screenshot.

**Comment by shah** [comment]
@raphaelvp @ratheesh-kr please review with @alan-francis and see if we need to update the CSV FHIR generator. For FHIR the IG and HAPI should handle it.

**Comment by alan-francis** [comment]
@reeager : We will update the race and ethnicity as per the code for the respective extensions as directed in the IG. This means whenever the race is coming as `American Indian or Alaska Native|Asian|Black or African American|Native Hawaiian or Other Pacific Islander|White` we will place them in the `ombCategory`  and all others will be placed in the `detailed`. Similar to this whenever the ethnicity is coming as `Hispanic or Latino|Not Hispanic or Latino` we will place them in the `ombCategory`  and all others will placed in the `detailed`. 
@reeager : If u can confirm this, we can update this in our next release.

@shah @raphaelvp @ratheesh-kr

**Comment by alan-francis** [comment]
@reeager : Since you did not get time to respond, we are going ahead and implementing this and will release by today morning as version 0.42.0 in devl.

@shah @raphaelvp @ratheesh-kr
