### ISSUE TITLE
Start to build out referral FHIR to FHIR validations

### ISSUE THREAD

**Issue by reeager** [qe-collaborative-services/1115-hub#203]
https://djq7jdt8kb490.cloudfront.net/1115/index.html 

Please see service request, task and procedure examples.

**Comment by shah** [comment]
@ratheesh-kr @raphaelvp please prioritize for review on Thursday and talk with me in case you have questions.

**Comment by ratheesh-kr** [comment]
Here are the steps we did.
Downloaded the files under the section: [New York 1115 Medicaid Waiver JSON Example](https://djq7jdt8kb490.cloudfront.net/1115/index.html) 

* Service Request Example
* Task Example
* Task Completed Example
* Procedure Completed Example

We validated this examples and the [results ](https://github.com/tech-by-design/docs.techbd.org/tree/main/assurance/1115-waiver/ahc-hrsn/screening/regression-test-prime/fhir-service-prime/src/2024-06-27/output) were added. 


These payloads are making through the techbd end points, If the QE is  sent it through techbd that also will work. Please review and let us know anything more need to do.

@reeager @shah @raphaelvp
