### ISSUE TITLE
Support Content-Type application/fhir+json as well as application/json

### ISSUE THREAD

**Issue by fredharmonbcbsscgit** [qe-collaborative-services/1115-hub#204]
When we call your endpoint we get a 415 Unsupported Content type.  https://www.hl7.org/fhir/http.html#mime-type

You should supoprt both types but at a minimum must support application/fhir+json.

![image](https://github.com/qe-collaborative-services/1115-hub/assets/141929243/1749cb93-2ddf-4d70-bd22-72f0162bd449)

@shah

**Comment by fredharmonbcbsscgit** [comment]
@raphaelvp @ratheesh-kr

**Comment by shah** [comment]
Understood @fredharmonbcbsscgit this will be completed and released as part of https://github.com/tech-by-design/polyglot-prime/issues/72.
