### ISSUE TITLE
Implement the business rules validation based on the "Omnibus Rules" specification

### ISSUE THREAD

**Issue by raphaelvp** [qe-collaborative-services/1115-hub#29]
Create reference CSV files based on the business rules and reference data from the "Omnibus Rules" specification document located at `support/docs/specifications/ahc-hrsn-elt/screening` directory.

Implement the validation rules based on the specification.

**Comment by shah** [comment]
@reeager has provided a new version of the specifications document and screening sample in [specifications/ahc-hrsn-elt/screening](support/docs/specifications/ahc-hrsn-elt/screening) directory.

**Comment by raphaelvp** [comment]
Resolved by #50, #51
