### ISSUE TITLE
Accept grouped ingress files bundled in a ZIP file

### ISSUE THREAD

**Issue by raphaelvp** [qe-collaborative-services/1115-hub#47]
The data ingestion should support the ingestion of grouped three-file (screening, QE admin, patient demographics) bundled as a ZIP file in addition to the CSV files.

The implementation should open the ZIP file and look for pattern `SCREENING*.csv`, `QE_ADMIN_DATA*.csv` and `DEMOGRAPHIC_DATA*.csv`. If these three files are present, unzip the files into the `egress/.consumed` directory, rename the files by appending the ZIP file name plus a unique session ID to the CSV files.

After the files are unzipped, ingest the files similar to how physical non-zipped CSV files are already ingested.

For example, if the ZIP file name is `ABC_20240301.zip` and it contains the files `SCREENING_123.csv`, `QE_ADMIN_DATA_123.csv` and `DEMOGRAPHIC_DATA_123.csv`, the files will be renamed to `SCREENING_123_ABC_20240301.csv`, `QE_ADMIN_DATA_123_ABC_20240301.csv` and `DEMOGRAPHIC_DATA_123_ABC_20240301.csv`.

**Comment by alan-francis** [comment]
We have updated the implementation to unzip the zip files to the ` egress/.ingress-tx ` folder and then ingest the unzipped files similar to how the physical non-zipped CSV files are already ingested.

**Comment by raphaelvp** [comment]
Resolved by #117. Released in 0.15.0
