### ISSUE TITLE
Implement aggregated content storage

### ISSUE THREAD

**Issue by raphaelvp** [qe-collaborative-services/1115-hub#48]
![Sequence Diagram](https://planttext.com/api/plantuml/svg/TPB1ReCm38RlUGgBoqxZ0JPfwYYhggcJsj5ZBo6OWWOnSXmctdw1jXjInobHyllp9oSh9vh5juq2q5x8-ZP7LaeR8OOratsdNA6LMWQ8iirn3nboZtooRh1IeTGcTgLqiQ2fyY8cFaUW7OnHbMhHkNO8qMrtigatNsaoPTBaHjxK3MQ34soLkZQ5nvS90a-m9clH20W1QbF1uUtXqW0gQX5AQehWFAlxmuNg51iKX8wnhyaxS8OOZUOYBe9AaIyMlXg3pW6UULmkNTmydIQZ7ACEU8lVTsIexKnumNKEoGuxwEj0AiFm6JjYkOj-UlkRMrJFmkiXa9VEopZfxV5ZzyzWzuqsE5sEgjFXLL2jq1RXMpp_0000)

[Edit Diagram](https://planttext.com/?text=TPB1ReCm38RlUGgBoqxZ0JPfwYYhggcJsj5ZBo6OWWOnSXmctdw1jXjInobHyllp9oSh9vh5juq2q5x8-ZP7LaeR8OOratsdNA6LMWQ8iirn3nboZtooRh1IeTGcTgLqiQ2fyY8cFaUW7OnHbMhHkNO8qMrtigatNsaoPTBaHjxK3MQ34soLkZQ5nvS90a-m9clH20W1QbF1uUtXqW0gQX5AQehWFAlxmuNg51iKX8wnhyaxS8OOZUOYBe9AaIyMlXg3pW6UULmkNTmydIQZ7ACEU8lVTsIexKnumNKEoGuxwEj0AiFm6JjYkOj-UlkRMrJFmkiXa9VEopZfxV5ZzyzWzuqsE5sEgjFXLL2jq1RXMpp_0000)

- [x] Create script to merge multiple `egress/<session-id>/.workflow/*.duckdb` databases into a single DuckDB database
- [ ] Implement the code to push the aggregated content data to Amazon Aurora PostgreSQL
- [ ] Create a CronJob to run the daily report in production synthetic.sftp.techbd.org every morning at 3am EDT.
  - [ ] At every run, delete the previous scorecard.duckdb then run through all `egress` folders and create a new `scorecard.duckdb` and place  into each QE's SFTP home folder.
  - [ ] Prepare an SQL view to generate a report of total number of submitted files, generated JSON files, etc. and other aggregations.
  - [ ] Run the view and store the output as HTML so that any non-technical user can see it.

**Comment by shah** [comment]
This is now implemented in TechBD Hub Polyglot Prime repo.
