### ISSUE TITLE
Error when setting up SFTP to QCS.

### ISSUE THREAD

**Issue by TOdellRRHIO** [qe-collaborative-services/1115-hub#58]
RRHIO recieved a report when trying to connect SFTP to QCS with the following error:
We were under the impression that this was password only.  Please advise.

![SFTP_issue](https://github.com/qe-collaborative-services/1115-hub/assets/161380456/6dbf10c2-1836-4c34-8a94-1392143c471b)

**Comment by shah** [comment]
@mdvertola please check to see if anything has changed on our SFTP end.

**Comment by mdvertola** [comment]
Nothing changed on our end with SFTP; just a quick call out that we are currently using port 2222, not 22. I'm not sure if that could be the issue here, but I would definitely double-check what port you are attempting to connect through, as 22 is typically the default for most SFTP clients.

**Comment by mdvertola** [comment]
@TOdellRRHIO If you are having further issues with this, let me know, i am happy to help debug.

**Comment by TOdellRRHIO** [comment]
We are following up with our off shore team.

**Comment by TOdellRRHIO** [comment]
Good morning, @mdvertola We would most likely need a call with our teams to establish a connecting.  Can you provide some time frames?  We are hoping to get connection established ASAP.

**Comment by shah** [comment]
@TOdellRRHIO please send an email to qcs-help@qualifiedentity.org and they'll help coordinate a call (best to take it outside of GitHub since this is a public discussion group).

**Comment by TOdellRRHIO** [comment]
Should this ticket be open till the issue is solved?

**Comment by shah** [comment]
@TOdellRRHIO since you've sent an email to [qcs-help@qualifiedentity.org](mailto:qcs-help@qualifiedentity.org) and this is an environmental issue within RRHIO the ticket has been closed. Continue the private conversations via e-mail since GitHub is a public repo and no private or sensitive conversations about authentication/authorization should take place here.
