### ISSUE TITLE
New Omnibus File Uploaded

### ISSUE THREAD

**Issue by reeager** [qe-collaborative-services/1115-hub#59]
New Omnibus File Uploaded dated 03-07. Please see change log for changes. 
[ahc-hrsn-2024-03-07-omnibus-rules.xlsx](https://github.com/qe-collaborative-services/1115-hub/files/14530033/ahc-hrsn-2024-03-07-omnibus-rules.xlsx)

**Comment by reeager** [comment]
[ahc-hrsn-2024-03-08-omnibus-rules.xlsx](https://github.com/qe-collaborative-services/1115-hub/files/14541344/ahc-hrsn-2024-03-08-omnibus-rules.xlsx)
Now updated. Please see change log.

**Comment by raphaelvp** [comment]
Updated changes to the rule by #68
