### ISSUE TITLE
FHIR Issues 

### ISSUE THREAD

**Issue by reeager** [qe-collaborative-services/1115-hub#69]
1.	Organization was missing lots of information.  Specifically, lastUpdated was blank.  Lots of other fields were blank.  Blank items should typically just be left out completely.
2.	Encounter type code is an integer that needs to be wrapped in ""
3.	MPI missing from identifiers list for Patient resource.  Add it using type "NP".

**Comment by raphaelvp** [comment]
Resolved by #71
