### ISSUE TITLE
Introduce orchestration HTTP service

### ISSUE THREAD

**Issue by raphaelvp** [qe-collaborative-services/1115-hub#72]
- [x] Add support for receiving screening files grouped in one or more `.zip` files over HTTP using multipart MIME attachments
- [ ] Allow optional _enrichment_ via webhooks by sending the interim DuckDB file to webhook before performing validation and then taking updated DuckDB file to perform validation
- [ ] Provide Swagger (OpenAPI) endpoints for documentation (using middleware or second HTTP server via containers)
- [ ] Define HTTP authentication strategy

![https://raw.githubusercontent.com/qe-collaborative-services/1115-hub/main/support/docs/qcs-http-service.drawio.svg](https://raw.githubusercontent.com/qe-collaborative-services/1115-hub/main/support/docs/qcs-http-service.drawio.svg)

**Comment by shah** [comment]
This is now implemented in TechBD Hub Polyglot Prime repo.
