### ISSUE TITLE
Fixes needed to diagnostics. 

### ISSUE THREAD

**Issue by reeager** [qe-collaborative-services/1115-hub#75]
Please see comments. 
[diagnostics_Healthix_RE Feedback_3.17.2024.xlsx](https://github.com/qe-collaborative-services/1115-hub/files/14628570/diagnostics_Healthix_RE.Feedback_3.17.2024.xlsx)

**Comment by raphaelvp** [comment]
[diagnostics_Healthix_RE.Feedback_3.17.2024.xlsx](https://github.com/qe-collaborative-services/1115-hub/files/14637682/diagnostics_Healthix_RE.Feedback_3.17.2024.xlsx)

Updated comments based on release [0.8.4](https://github.com/qe-collaborative-services/1115-hub/releases/tag/0.8.4)
