### ISSUE TITLE
JSON edits

### ISSUE THREAD

**Issue by reeager** [qe-collaborative-services/1115-hub#77]
Please find comments and changes needed  regarding your JSON: 
[QCS JSON_3.19.2024_RRHIO Test.docx](https://github.com/qe-collaborative-services/1115-hub/files/14650298/QCS.JSON_3.19.2024_RRHIO.Test.docx)

**Comment by fredharmonbcbsscgit** [comment]
Encounter Class structured incorrectly.  Currently seeing:

`"class": [
          {
            "coding": [
              {
                "system": "[http://terminology.hl7.org/CodeSystem/v3-ActCode"](http://terminology.hl7.org/CodeSystem/v3-ActCode%22),
                "code": "NONAC"
              }
            ]
          }
        ],`

Should be formatted like the following as shown in the IG sample.:

`"class": {
          "system": "[http://terminology.hl7.org/CodeSystem/v3-ActCode"](http://terminology.hl7.org/CodeSystem/v3-ActCode%22),
          "code": "NONAC"
        },`

**Comment by fredharmonbcbsscgit** [comment]
Patient communication structure incorrectly.  Currently seeing:

`  "communication": [
          {
            "language": {
              "coding": [
                "code",
                "heb"
              ]
            },
            "preferred": true
          }
        ]`

Should look like this based on the IG Sample:

`  "communication": [
          {
            "language": {
              "coding": [
                {
                  "code": "heb"
                }
              ]
            },
            "preferred": true
          }
        ]`

**Comment by fredharmonbcbsscgit** [comment]
Not seeing a "Consent" resource included in the FHIR bundle.

**Comment by fredharmonbcbsscgit** [comment]
Seeing a number of places (4 or 5) where `"code": null` .  A couple of examples below:  

Observation Resources:

`        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": null,
              "display": "Calculated mental health score"
            }
          ]
        },`

`        "valueCodeableConcept": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": null,
              "display": "180"
            }
          ]`

**Comment by raphaelvp** [comment]
> Encounter Class structured incorrectly. Currently seeing:
> 
> `"class": [ { "coding": [ { "system": "[http://terminology.hl7.org/CodeSystem/v3-ActCode"](http://terminology.hl7.org/CodeSystem/v3-ActCode%22), "code": "NONAC" } ] } ],`
> 
> Should be formatted like the following as shown in the IG sample.:
> 
> `"class": { "system": "[http://terminology.hl7.org/CodeSystem/v3-ActCode"](http://terminology.hl7.org/CodeSystem/v3-ActCode%22), "code": "NONAC" },`

Resolved by #78

**Comment by raphaelvp** [comment]
> Patient communication structure incorrectly. Currently seeing:
> 
> ` "communication": [ { "language": { "coding": [ "code", "heb" ] }, "preferred": true } ]`
> 
> Should look like this based on the IG Sample:
> 
> ` "communication": [ { "language": { "coding": [ { "code": "heb" } ] }, "preferred": true } ]`

Resolved by #78

**Comment by raphaelvp** [comment]
> Not seeing a "Consent" resource included in the FHIR bundle.

Resolved by #78

**Comment by raphaelvp** [comment]
Resolved by 0.9.0
