### ISSUE TITLE
Issues with Version 0.8.5

### ISSUE THREAD

**Issue by fredharmonbcbsscgit** [qe-collaborative-services/1115-hub#79]
**Issue 1:**
We ran a set of tests with HealtheConnections this morning. We sent them 25 test cases. They dropped all the 75 test files associated with these test cases into their SFTP and they were processed by QCS. We got a bundle which I have attached. We see that many of the same test cases for differnt patient all ended up in the same bundle. A bundle that is sent to our API should be for a single patient with their screenings.  The bundle can have multiple encounters, multiple observations, multiple organizations, 1 consent and 1 patient.

The bundle we recieved on the API is attached.
[HealtheConnections.json](https://github.com/qe-collaborative-services/1115-hub/files/14670440/HealtheConnections.json)

**Issue 2 :**

Invalid Consent Category Formatting.  You sent

`        "category": {
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
              "code": "IDSCL"
            }
          ]
        },`

It should look like:
`        "category": [
          {
            "coding": [
              {
                "code": "59284-0",
                "display": "Patient Consent"
              }
            ]
          }
        ],`

**Issue 3 :**

In Consent, "datetime" needs to be "dateTime".

You sent:

`"datetime": "2024-01-26 00:21:16.6216410",`

It should be:

`"dateTime": "2024-01-26 00:21:16.6216410",`

**Issue 4 :**

In Patient identifiers, we found the MPI "PT" type had the MPI as an integer and not a string:

You sent this:
`          {
            "type": {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                  "code": "PN"
                }
              ]
            },
            "system": "http://www.acme.com/identifiers/patient",
            "value": 13196912
          }`

It needs to be 

`          {
            "type": {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                  "code": "PN"
                }
              ]
            },
            "system": "http://www.acme.com/identifiers/patient",
            "value": "13196912"
          }`

Issue 5:

Encounter type not formatted like the IG:

You are currently sending:

     `   "type": [
          {
            "coding": [
              {
                "system": 185317003,
                "code": null
              }
            ]
          }
        ],  `

It should look like:

`        "type": [
          {
            "coding": [
              {
                "system": "http://snomed.info/sct",
                "code": "405672008",
                "display": "Direct questioning (procedure)"
              }
            ],
            "text": "Direct questioning (procedure)"
          }
        ],`

Issue 6:

Encounter status cannot be "null"

In some Encounters you sent the below.  This cannot be null and must be present with a value.

`"status": null `

Issue 7:

Consent organizatoin references should be a list type object.  The IG does not have an example.

You are currently sending it like:

`        "organization":           {
            "reference": "Organization/CNYSCN"
          }
`

Should be sent like:
`        "organization": [
          {
            "reference": "Organization/CNYSCN"
          }
        ]`

**Comment by fredharmonbcbsscgit** [comment]
@raphaelvp

**Comment by fredharmonbcbsscgit** [comment]
@reeager

**Comment by fredharmonbcbsscgit** [comment]
@shah

**Comment by raphaelvp** [comment]
Resolved by #80

**Comment by reeager** [comment]
Please see issue #102 multiple encounters should not exist in a single bundle.
