### ISSUE TITLE
Create and maintain Reference Data README.md

### ISSUE THREAD

**Issue by shah** [qe-collaborative-services/1115-hub#81]
Create and maintain a README.md file in [Reference Data](https://github.com/qe-collaborative-services/1115-hub/tree/main/src/ahc-hrsn-elt/reference-data) that describes the purpose of each reference file, where it was sourced from (e.g. Omnibus Rules sheet or other location), and most importantly whether any transformations and additions were done from the source to the destination.

There should be sufficient detail for each file to serve as a lineage artifact for data governance purposes.

**Comment by raphaelvp** [comment]
Resolved by #92, released in 0.10.3
