### ISSUE TITLE
Issues with v.0.10.0

### ISSUE THREAD

**Issue by fredharmonbcbsscgit** [qe-collaborative-services/1115-hub#88]
Issue 1:  Our validator generates the error " An unexpected validation error occurred parsing FHIR: {root}:  entry.27:    resource:      Non-optional property code on <fhir.resources.observation.Observation object at 0x7ff4a5d418b0> is missing" due to invalid FHIR.

There are several Observations (examples: observationResponseQuestion_20 and observationResponseQuestion_27) where you do not include a "code" element on the Observation.  This creates invalid FHIR based on the R4 specification.  It is also mandatory based on the SHINNY IG.  I stubbed in a code to these two and was able to see some test start passing.  We should come up with a null flavor code for you to pass in the case where these two quetsions don't have LOINCS.

These are for the two "Calculated" questions that don't have LOINC codes.  The IG has you add codes that look like:

`        "code": {
          "coding": [
            {
              "display": "Calculated weekly physical activity"
            }
          ]
        },
`

`        "code": {
          "coding": [
            {
              "display": "Calculated mental health score"
            }
          ]
        },
`

Issue 2:  Our validator failed with the error " An unexpected validation error occurred parsing FHIR: {root}:  entry.1:    resource:      extension:        name self is not defined"  This was previously reported in a prior engine version.   To help track this down, this was for rochester, testcase 27, on 2024-03-22 tests case date that ran through the engine the morning of 3/26/2024.  I can provide the inputted CSV if you can't find it.

You are sending this extension in the Patient resource:

`                "extension": [
                    null,
                    {
                        "extension": [
                            {
                                "url": "ombCategory",
                                "valueCoding": {
                                    "system": "urn:oid:2.16.840.1.113883.6.238",
                                    "code": "2142-8",
                                    "display": "Belearic Islander"
                                }
                            }
                        ],
                        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity"
                    },
                    null,
                    null
                ],`

The nulls need to be removed.

@raphaelvp @reeager @shah

**Comment by raphaelvp** [comment]
Resolved by #91
