### ISSUE TITLE
Remove Spaces from ADMINISTRATIVE_SEX fields in QCS diagnostics and FHIR codes

### ISSUE THREAD

**Issue by reeager** [qe-collaborative-services/1115-hub#89]
- Ready will no longer be sending spaces in ADMINISTRATIVE_SEX _CODE_SYSTEM and ADMINISTRATIVE_SEX _CODE_DESCRIPTION. Please ensure that your diagnostics and FHIR is able to utilize the column names with no spaces.

**Comment by reeager** [comment]
@DrewMcN

**Comment by reeager** [comment]
@fredharmonbcbsscgit

**Comment by raphaelvp** [comment]
Resolved by #91
