### ISSUE TITLE
UTF Issue- HeL

### ISSUE THREAD

**Issue by reeager** [qe-collaborative-services/1115-hub#95]
We are having trouble with ingesting HeL files into the data lake because of improperly formatted meta.lastUpdated timestamps. . This isn't an issue with other QEs. We need this in UTF to be ingested.

**Comment by reeager** [comment]
@tking-healthelink @hgallson

**Comment by reeager** [comment]
@tking-healthelink Sorry I did mean UTC! But I am seeing +05:00 not +0500 in the data.

**Comment by tking-healthelink** [comment]
@reeager Sorry, I just abbreviated the timezone as +0500, both the CSV we get from Ready, and the generated fhir json from QCS have  +05:00:

    "meta": {
        "lastUpdated": "1995-03-04T21:45:04.593723+05:00"
    },

...RSN) tool|[http://loinc.org|1995-03-04T21:45:04.593723+05:00|71802-3...

**Comment by shah** [comment]
@tking-healthelink I think this has been resolved so I'll close it. If this is still an issue, please reopen it.
