### ISSUE TITLE
Issues with v0.10.4

### ISSUE THREAD

**Issue by n-kes** [qe-collaborative-services/1115-hub#98]
**Issue 1: [HeC specific] -** 

We are seeing submissions from HealtheConnections fail the validator because:

- encounter.type.coding.system and should be a JSON string (FHIR datatype URI).
- encounter.type.coding.code is not present
- encounter.type.coding.display contains what appears to be the value for encounter.type.coding.system
- encounter.type.coding.system contains what appears to be the value for encounter.type.coding.code

Before (broken):

```
                "type": [
                    {
                        "coding": [
                            {
                                "system": 453701000124103,
                                "display": "http://snomed.info/sct"
                            }
                        ],
                        "text": "http://snomed.info/sct"
                    }
                ],
```

After (fixed):

```
                "type": [
                    {
                        "coding": [
                            {
                                "system": "http://snomed.info/sct",
                                "code": "453701000124103"
                            }
                        ]
                    }
                ],

```

**Issue 2: [HeC specific] -** 

We are seeing submissions from HealtheConnections fail the validator because:

- encounter.class.system contains what appears to be the value for encounter.class.code
- encounter.class.code is not present

Before (broken):

```
                "class": {
                    "system": "FLD"
                },
```

After (fixed):

```
                "class": {
                    "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
                    "code": "FLD"
                },
```

@ghoward9 @raphaelvp @reeager @shah

**Comment by raphaelvp** [comment]
FHIR JSON is generated incorrectly because the input data file contain invalid data.

Please review the diagnostics.xlsx generated in the egress folder to identify the issues with the input data. Attached the diagnostics.xlsx file generated from this test run here for reference. 
[diagnostics.xlsx](https://github.com/qe-collaborative-services/1115-hub/files/14836033/diagnostics.xlsx)
